[package]
name = "exonum-cryptoowls"
version = "0.0.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com"
repository = "https://github.com/exonum/exonum-cryptoowls"
readme = "README.md"
license = "Apache-2.0"
publish = false

[dependencies]
display_derive = "0.0.0"
exonum = "0.6.0"
exonum-time = "0.6.0"
failure = "0.1.1"
failure_derive = "0.1.1"
iron = "0.6.0"
bodyparser = "0.8.0"
log = "0.4.0"
mount = "0.4.0"
rand = "0.4.2"
router = "0.6.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
byteorder = "1.2.1"

[dev-dependencies]
exonum-testkit = "0.6.0"